// Códigos experimentales para empaquetar Synthi GME junto a los binarios de SuperCollider.
// *********************************************************


// Este comando devuelve el directorio SCClassLibrary, donde están todas las clases de SuperCollider (no Quarks, no Extensions). De este modo, se puede poner toda la app dentro de ese directorio y referenciar allí todos los recursos (imágenes, etc.).
Platform.classLibraryDir